### ISSUE TITLE
使用时的错误

### ISSUE THREAD

**Issue by DaSea** [larrycai/mkbok#1]
下面是我的使用步骤
1. 安装了mkbok；
2. 使用mkbok --generate生成了一个目录；
3. 进入目录，mkbok --build pdf 发生如下错误；
`var/lib/gems/2.3.0/gems/mkbok-0.0.14/bin/mkbok:264:in `read': Is a directory @ io_fread - /home/seasea/test/zh/ (Errno::EISDIR)`

不太懂ruby, 求解啊！

**Comment by larrycai** [comment]
建议直接看 https://github.com/larrycai/sdcamp ，这个项目已经废弃了，我都忘记了。

**Comment by DaSea** [comment]
Ok!
